### ISSUE TITLE
pdf加水印报错

### ISSUE THREAD

**Issue by heigeme** [a852203465/watermark#1]
我从服务器中请求pdf然后加水印,报错不支持文件格式为 text/html 的水印处理,但是从浏览器直接访问该url并没有问题,pdf也能下载下载,请教下什么问题呢

**Comment by a852203465** [comment]
你的PDF是什么格式？----是pdf文件(实体文件)，还是一段html（在网页中直接阅读的），还是别的格式




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "a852203465/watermark"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月9日(星期三) 上午10:46
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[a852203465/watermark] pdf加水印报错 (Issue #1)





 
我从服务器中请求pdf然后加水印,报错不支持文件格式为 text/html 的水印处理,但是从浏览器直接访问该url并没有问题,pdf也能下载下载,请教下什么问题呢
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by heigeme** [comment]
是pdf实体文件,先传到服务器上,然后点击下载的时候,我通过copyfile的方式,将新的file传入加水印的方法中,本地环境并没有问题,测试环境报错不支持文件格式为 text/html ,后来我把这块的权限去掉了,继续报错PDF header signature not found

**Comment by a852203465** [comment]
1. 请提供下报错信息“不支持文件格式为 text/html&nbsp;”当时的调用完整报错信息
2.&nbsp; PDF header signature not found： 请检查pdf文件是不是直接修改文件后缀名强行更改的





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "a852203465/watermark"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月11日(星期五) 下午3:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [a852203465/watermark] pdf加水印报错 (Issue #1)





 
是pdf实体文件,先传到服务器上,然后点击下载的时候,我通过copyfile的方式,将新的file传入加水印的方法中,本地环境并没有问题,测试环境报错不支持文件格式为 text/html ,后来我把这块的权限去掉了,继续报错PDF header signature not found
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by a852203465** [comment]
你好, pdf增加水印，提示：“不支持文件格式为 text/html 的水印处理”， 已经适配，你可以再次尝试使用





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "a852203465/watermark"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月11日(星期五) 下午3:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [a852203465/watermark] pdf加水印报错 (Issue #1)





 
是pdf实体文件,先传到服务器上,然后点击下载的时候,我通过copyfile的方式,将新的file传入加水印的方法中,本地环境并没有问题,测试环境报错不支持文件格式为 text/html ,后来我把这块的权限去掉了,继续报错PDF header signature not found
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
