### ISSUE TITLE
hutool

### ISSUE THREAD

**Issue by zfhplaycode** [a852203465/watermark#2]
您好，请问hutool的代码放在了什么位置？

**Comment by a852203465** [comment]
hutool包：是开源的JAVA工具包
hutool github:&nbsp;https://github.com/dromara/hutool


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "a852203465/watermark"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月17日(星期三) 上午10:07
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[a852203465/watermark] hutool (Issue #2)





 
您好，请问hutool的代码放在了什么位置？

**Comment by zfhplaycode** [comment]
请问在运行excel的时候提示
java.lang.NoClassDefFoundError: org/apache/xmlgraphics/image/loader/ImageContext
这个您有什么解决方案吗？

**Comment by a852203465** [comment]
引用依赖：


<dependency&gt;
   <groupId&gt;org.apache.xmlgraphics</groupId&gt;
   <artifactId&gt;xmlgraphics-commons</artifactId&gt;
   <version&gt;2.3</version&gt;
</dependency&gt;














------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "a852203465/watermark"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月17日(星期三) 下午2:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [a852203465/watermark] hutool (Issue #2)





 
请问在运行excel的时候提示
 java.lang.NoClassDefFoundError: org/apache/xmlgraphics/image/loader/ImageContext
 这个您有什么解决方案吗？

**Comment by zfhplaycode** [comment]
好的，感谢您的帮助，祝好！
