### ISSUE TITLE
大佬你的Aspose是破解版吗。

### ISSUE THREAD

**Issue by SpringStudent** [a852203465/watermark#3]

**Comment by a852203465** [comment]
是的，在网上找的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "a852203465/watermark"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月7日(星期二) 下午3:27
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[a852203465/watermark] 大佬你的Aspose是破解版吗。 (Issue #3)

**Comment by SpringStudent** [comment]
不会突然收费把，想用在自己的项目中

**Comment by a852203465** [comment]
应该不会的，&nbsp;license.xml是20991231到期的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "a852203465/watermark"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月7日(星期二) 下午3:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [a852203465/watermark] 大佬你的Aspose是破解版吗。 (Issue #3)





 
不会突然收费把，想用在自己的项目中

**Comment by SpringStudent** [comment]
好的，非常感谢
