### ISSUE TITLE
xls

### ISSUE THREAD

**Issue by MRwuyan** [a852203465/watermark#4]

**Comment by MRwuyan** [comment]
貌似xls不行,报错
![image](https://github.com/a852203465/watermark/assets/34454087/f2379820-ae05-4b83-8142-fdb20dc35617)

**Comment by a852203465** [comment]
你这个是JDK版本原因， 你是使用JDK21， 我是基于JDK8封装的， 你需要降低JDK版本

**Comment by a852203465** [comment]
你这个是JDK版本原因， 你是使用JDK21， 我是基于JDK8封装的， 你需要降低JDK版本

**Comment by MRwuyan** [comment]
哦哦,谢谢兄弟回复
